<a href="https://colab.research.google.com/github/AhsanDz/4-Ahsan/blob/main/EDA_Ahsan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

##Initial EDA

###Read File & Data Info

In [2]:
df = pd.read_csv('US_Accidents.csv')

df.head()

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-2047758,Source2,2,2019-06-12 10:10:56,2019-06-12 10:55:58,30.641211,-91.153481,NaN,NaN,0.000,...,False,False,False,False,True,False,Day,Day,Day,Day
1,A-4694324,Source1,2,2022-12-03 23:37:14.000000000,2022-12-04 01:56:53.000000000,38.990562,-77.399070,38.990037,-77.398282,0.056,...,False,False,False,False,False,False,Night,Night,Night,Night
2,A-5006183,Source1,2,2022-08-20 13:13:00.000000000,2022-08-20 15:22:45.000000000,34.661189,-120.492822,34.661189,-120.492442,0.022,...,False,False,False,False,True,False,Day,Day,Day,Day
3,A-4237356,Source1,2,2022-02-21 17:43:04,2022-02-21 19:43:23,43.680592,-92.993317,43.680574,-92.972223,1.054,...,False,False,False,False,False,False,Day,Day,Day,Day
4,A-6690583,Source1,2,2020-12-04 01:46:00,2020-12-04 04:13:09,35.395484,-118.985176,35.395476,-118.985995,0.046,...,False,False,False,False,False,False,Night,Night,Night,Night

In [4]:
df.shape

(500000, 46)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 46 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   ID                     500000 non-null  object
 1   Source                 500000 non-null  object
 2   Severity               500000 non-null  int64
 3   Start_Time             500000 non-null  object
 4   End_Time               500000 non-null  object
 5   Start_Lat              500000 non-null  float64
 6   Start_Lng              500000 non-null  float64
 7   End_Lat                279623 non-null  float64
 8   End_Lng                279623 non-null  float64
 9   Distance(mi)           500000 non-null  float64
 10  Description            499999 non-null  object
 11  Street                 499309 non-null  object
 12  City                   499981 non-null  object
 13  County                 500000 non-null  object
 14  State                  500000 non-null  object
 15  Zipcode                499884 non-null  object
 16  Country                500000 non-null  object
 17  Timezone               499493 non-null  object
 18  Airport_Code           498554 non-null  object
 19  Weather_Timestamp      492326 non-null  object
 20  Temperature(F)         489534 non-null  float64
 21  Wind_Chill(F)          370983 non-null  float64
 22  Humidity(%)            488870 non-null  float64
 23  Pressure(in)           491072 non-null  float64
 24  Visibility(mi)         488709 non-null  float64
 25  Wind_Direction         488803 non-null  object
 26  Wind_Speed(mph)        463013 non-null  float64
 27  Precipitation(in)      357384 non-null  float64
 28  Weather_Condition      488899 non-null  object
 29  Amenity                500000 non-null  bool
 30  Bump                   500000 non-null  bool
 31  Crossing               500000 non-null  bool
 32  Give_Way               500000 non-null  bool
 33  Junction               500000 non-null  bool
 34  No_Exit                500000 non-null  bool
 35  Railway                500000 non-null  bool
 36  Roundabout             500000 non-null  bool
 37  Station                500000 non-null  bool
 38  Stop                   500000 non-null  bool
 39  Traffic_Calming        500000 non-null  bool
 40  Traffic_Signal         500000 non-null  bool
 41  Turning_Loop           500000 non-null  bool
 42  Sunrise_Sunset         498517 non-null  object
 43  Civil_Twilight         498517 non-null  object
 44  Nautical_Twilight      498517 non-null  object
 45  Astronomical_Twilight  498517 non-null  object
dtypes: bool(13), float64(12), int64(1), object(20)
memory usage: 132.1+ MB

###Cek Missing Values

In [6]:
# Menghitung persentase missing values tiap kolom, diurutkan dari yang terbesar
missing_percentages = df.isnull().sum().sort_values(ascending=False) / len(df) * 100
print(missing_percentages[missing_percentages > 0]) # Hanya tampilkan yang ada missing value

End_Lng                  44.0754
End_Lat                  44.0754
Precipitation(in)        28.5232
Wind_Chill(F)            25.8034
Wind_Speed(mph)           7.3974
Visibility(mi)            2.2582
Wind_Direction            2.2394
Humidity(%)               2.2260
Weather_Condition         2.2202
Temperature(F)            2.0932
Pressure(in)              1.7856
Weather_Timestamp         1.5348
Sunrise_Sunset            0.2966
Civil_Twilight            0.2966
Astronomical_Twilight     0.2966
Nautical_Twilight         0.2966
Airport_Code              0.2892
Street                    0.1382
Timezone                  0.1014
Zipcode                   0.0232
City                      0.0038
Description               0.0002
dtype: float64

Karena kolom End_Lng dan End_Lat hampir 50% tidak memiliki nilai, maka kolom tersebut kemungkinan besar akan didrop.
Sedangkan, untuk yang lainnya bisa diimputasi

### Cek Distribusi Target

In [10]:
df['Severity'].value_counts(normalize=True) * 100

Severity
2    79.6284
3    16.9040
4     2.6128
1     0.8548
Name: proportion, dtype: float64

Data target sangat Imbalanced. Tingkat keparahan 2 mendominasi hingga hampir 80%, sementara tingkat 1 di bawah 1%.